### ISSUE TITLE
Joint Variant Calling

### ISSUE THREAD

**Issue by sklages** [sequencing/isaac_variant_caller#3]
Hi,

when analyzing many (human exome) samples for variant calling we usually align data using bwa and run the GATK pipeline including HaplotypeCaller for each resulting BAM separately. Finally we run GATKs GenotypeGVCFs with all VCF files created .. see [1]

In an alternative (testing) approach we run Platypus[2] on all bwa-aligned BAMs at once.

How do I best acomplish this task with isaac2 and ivc (starling)?

best,
Sven

[1]=https://www.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_variantutils_GenotypeGVCFs.php
[2]=https://github.com/andyrimmer/Platypus

**Comment by ctsa** [comment]
Hi Sven,

This version of the software is still fairly close the methods we described in the Isaac publication, so this is a single sample workflow. You can provide a vcf of candidate indels from population/cohort for this version of the caller. To do so add the extra argument:

    extraIvcArguments = --candidate-indel-input-vcf indels.vcf.gz 

To the config file here:

https://github.com/sequencing/isaac_variant_caller/blob/master/etc/ivc_config_default_wgs.ini#L70

IVC is essentially the single-sample version of strelka, so you can find several other custom configuration arguments described for strelka [here](https://sites.google.com/site/strelkasomaticvariantcaller/home/configuration-and-analysis/configuration-extrastrelkaoptions). 

Our goal is to provide public updates for the small variant callers with the accompanying GPLv3 license switch in the near future, following the pattern of the recent [Isaac2](https://github.com/Illumina/isaac2) and [manta](https://github.com/Illumina/manta) software updates. Hope to be able to provide an update on that soon.

-Chris

**Comment by sklages** [comment]
Hi Chris,
thanks for the info.
I'll have a look.

I'd go for directly using HaplotypeCaller on isaac2-aligned (human) exome data. Do you expect any problems using the BAM file directly without further pre-processing as GATK "best pratices" recommends? Do you have experience with this combination of tools?

best,
Sven

**Comment by ctsa** [comment]
I don’t know of any prior reason it shouldn’t work, you might enter this as an issue for isaac2 if you feel like there should be more documentation on the subject.
